### ISSUE TITLE
求助，安卓版本打包编译失败

### ISSUE THREAD

**Issue by 1206660** [zengdelang/slua-unreal-pb#1]
环境：UE4.21.2
NDK toolchain: r16b, NDK version: 27, GccVersion: 4.9, ClangVersion: 5.0.300080

编译错误如下：
PackagingResults: Error: use of undeclared identifier 'UE4CodeGen_Private'
UATHelper: Packaging (Android (ASTC)):    C:/svn/slua_unreal/Source/Plugins/slua_unreal/Source/slua_unreal/Public\PropertyUtil.h(24,22):  note: expanded from macro 'DefDeduceType'
UATHelper: Packaging (Android (ASTC)):             static const UE4CodeGen_Private::EPropertyClass value = UE4CodeGen_Private::EPropertyClass::B; \
UATHelper: Packaging (Android (ASTC)):                          ^
UATHelper: Packaging (Android (ASTC)):     fatal error: too many errors emitted, stopping now [-ferror-limit=]
UATHelper: Packaging (Android (ASTC)):     20 errors generated.
PackagingResults: Error: use of undeclared identifier 'UE4CodeGen_Private'
PackagingResults: Error: use of undeclared identifier 'UE4CodeGen_Private'
PackagingResults: Error: use of undeclared identifier 'UE4CodeGen_Private'
...
PackagingResults: Error: too many errors emitted, stopping now [-ferror-limit=]

**Comment by zengdelang** [comment]
PropertyUtil是slua-unreal项目自身的源码，你去他们项目下问下
