### ISSUE TITLE
Lua属性同步

### ISSUE THREAD

**Issue by 616050468** [zengdelang/slua-unreal-pb#3]
想问一下，Lua的Rpc和属性同步是怎么搞得？思路是怎样的？

**Comment by zengdelang** [comment]
主要的思想，采用Lua和蓝图配合的方式

**Comment by zengdelang** [comment]
1 把属性同步和RPC调用方法在蓝图中声明
2 Lua,我在我自己的面向对象基础上实现了UObjectClass用于RPC和属性同步
![image](https://user-images.githubusercontent.com/4466062/60769280-3f903c80-a100-11e9-9d33-8ee3349a2ed4.png)
![image](https://user-images.githubusercontent.com/4466062/60769285-46b74a80-a100-11e9-9f59-bd262d5c72fa.png)

**Comment by zengdelang** [comment]
3 修改LuaActor的方法，重载ProcessEvent和GetFunctionCallspace，
![image](https://user-images.githubusercontent.com/4466062/60769300-7a927000-a100-11e9-9298-cd27a4bcd988.png)
![image](https://user-images.githubusercontent.com/4466062/60769301-84b46e80-a100-11e9-80c1-9322c51d6461.png)
![image](https://user-images.githubusercontent.com/4466062/60769307-8e3dd680-a100-11e9-8685-573306867dd0.png)

**Comment by zengdelang** [comment]
最后的测试方法：
![image](https://user-images.githubusercontent.com/4466062/60769337-fdb3c600-a100-11e9-947e-b7cb7d3c33c3.png)
最后是我这边没有使用LuaActor，而是自己实现了LuaBaseActor，如果改LuaActor我没测试过，另外我是自己实现了一套面向对象，可能做法有点不兼容，需要你自己测试，测试的方法主要是和单独使用蓝图的RPC和属性同步的结果进行对比，保证是否调用一致

**Comment by zengdelang** [comment]
实在搞不定我可以把我的整套lua框架开源给你看下，也不是什么秘密

**Comment by 616050468** [comment]
噢噢，我看了你的方案，其实slua现在已经支持ProcessEvent了。属性同步这里有点没懂？CallRepNotify是服务端使用的，还是蓝图回调？没看到在哪里触发同步？

**Comment by zengdelang** [comment]
我就是基于slua的ProcessEvent重构的，不过单那样是不够的，CallRepNotify是服务器的代码调用的，同步是在UObject的ProcessEvent中自动同步的
