### ISSUE TITLE
萌新求教，大佬有没有简单的使用demo参考一下？

### ISSUE THREAD

**Issue by casper-yj** [zengdelang/slua-unreal-pb#4]
萌新求教，大佬有没有简单的使用demo参考一下？

**Comment by zengdelang** [comment]
参考Lua-protobuf的使用指南

**Comment by zengdelang** [comment]
可以把lua-protobuf的protoc.lua拿来研究，protoc.lua可以直接使用protobuf的定义来使用，不需要编译

**Comment by casper-yj** [comment]
多谢大佬，已经跑通。可以关闭啦
