### ISSUE TITLE
求助，安卓版本loadfile失败

### ISSUE THREAD

**Issue by casper-yj** [zengdelang/slua-unreal-pb#5]
local n = pb.loadfile(gm.GetFilePath().."/proto/network_protocol.pb")
print(n)

gm.GetFilePath()  是 FPaths::ProjectContentDir()
ue4 4.22.3
vs 2017

结果:
n  nil
怀疑是 loadfile 中用了fopen 所导致？
请教是否会有这个问题？

**Comment by zengdelang** [comment]
不要用文件读取pb，而是把pb当作UE的asset打包，然后读取

**Comment by zengdelang** [comment]
修改打包路径
![image](https://user-images.githubusercontent.com/4466062/63852720-8cd7ae80-c9cb-11e9-86f7-7dff81e80ae3.png)

读取pb资源文件，push到lua中
![image](https://user-images.githubusercontent.com/4466062/63852802-b4c71200-c9cb-11e9-95a7-a9fc2b33851a.png)

![image](https://user-images.githubusercontent.com/4466062/63852793-ac6ed700-c9cb-11e9-81b8-fbf28ccf5ad0.png)

**Comment by zengdelang** [comment]
lua中加载pb

![image](https://user-images.githubusercontent.com/4466062/63852936-0bcce700-c9cc-11e9-8257-7ffd71f928fe.png)

**Comment by casper-yj** [comment]
请教 require("Logic/Network/ProtocolDefines")  这个是啥模块？

**Comment by zengdelang** [comment]
这是我自己写的一个模块，通过工具一键编译所有的pb文件，自动生成一个pb列表的table的lua文件

**Comment by casper-yj** [comment]
那如果我只有单个 .pb文件 lua部分应该怎么加载？

**Comment by casper-yj** [comment]
![image](https://user-images.githubusercontent.com/11566445/63862394-13e25200-c9df-11e9-96f8-928460d29f0c.png)
红框内的是啥？

**Comment by zengdelang** [comment]
pb.load(LuaHelperLibrary.LoadPBFile(pbPath))就行

**Comment by zengdelang** [comment]
这是我的项目的pb保存路径的前缀

**Comment by zengdelang** [comment]
应该放在了Content目录下的Dev/ProtoFiles/,就是这个前缀

**Comment by casper-yj** [comment]
感谢大佬，成功了
